# site
title: Com Ballar
url: "http://comballar.github.io"
favicon: "/assets/crystal_icon.png"
g_analytics: UA-12345678-1

# bio
header: Com Ballar
desc: >

# posts
date_format: "%Y"

collections:
  journals:
    output: true
    permalink: /:collection/:title
    
# journals
journal_title: Entry
journal_date: Year
journal_cat: Category

# journal detail
prev-next: true

# build settings
markdown: kramdown
#theme: fry
exclude:
  - Gemfile
  - Gemfile.lock
