# site
title: Como Ballar
url: "http://comoballar.github.io"
favicon: "/assets/images/favicon.png"
g_analytics: UA-12345678-1

# bio
header: Como Ballar
desc: >

# posts
date_format: "%Y"

collections:
  journals:
    output: true
    permalink: /:collection/:title
    
# journals
journal_title: Entry
journal_date: Year
journal_cat: Category

# build settings
markdown: kramdown
#theme: fry
exclude:
  - Gemfile
  - Gemfile.lock
