# site
title: com ballar
url: "http://comballar.github.io"
favicon: "/assets/icon.png"
g_analytics: UA-12345678-1

# bio
header: com ballar
desc: >
  cultivating a lush inner/outer world.

# posts
date_format: "%d %B %Y"
post_title: Story
post_date: Date
post_cat: Category

# post detail
prev-next: true

# build settings
markdown: kramdown
#theme: louie
exclude:
  - Gemfile
  - Gemfile.lock
