# site
title: com ballar
url: "http://comballar.github.io"
favicon: "/assets/icon.png"
g_analytics: UA-12345678-1

# bio
header: com ballar
desc: >
  cultivating a lush inner/outer world. <a href="https://comballar.github.io/about/">more about me »</a>

# posts
date_format: "%d %b %Y"
post_title: Title
post_date: Date
post_cat: Category

# post detail
prev-next: true

# build settings
markdown: kramdown
#theme: louie
exclude:
  - Gemfile
  - Gemfile.lock
