# site
title: com ballar
baseurl: "/louie"
url: "http://comballar.github.io"
favicon: "/assets/sample/ico.png"
g_analytics: UA-12345678-1

# bio
header: com ballar
desc: >
  A Jekyll theme (that looks awesome). Louie is free, lightweight,
  and customizable as a blog, archive, or portfolio.

# posts
date_format: "%Y"
post_title: Story
post_date: Year
post_cat: Genre

# post detail
prev-next: true

# build settings
markdown: kramdown
theme: louie
exclude:
  - Gemfile
  - Gemfile.lock
